import assert from 'node:assert/strict';
import test from 'node:test';
import { acceptContract, acquireAircraft, acquireMarketOffer, claimContract, configureCabin, createNewGame, createRoute, financialStatement, hydrateGameState, mitigateEvent, openHub, processSimulation, repayLoan, setCompanyAvatar, takeLoan, upgradeInfrastructure } from '../app/game/engine';
import { validateGame } from '../app/game/storage';
import type { GameState } from '../app/game/types';

function game(){return createNewGame({playerName:'Teste',name:'Teste Linhas Aéreas',iata:'TL',icao:'TLA',callsign:'TESTE',country:'Brasil',base:'GRU',primaryColor:'#0c3153',secondaryColor:'#59d6c7',difficulty:'normal'});}

test('aquisição desconta caixa, individualiza aeronave e registra transação',()=>{const before=game(),result=acquireAircraft(before,'c208','new');assert.equal(result.error,undefined);assert.equal(result.state.fleet.length,1);assert.ok(result.state.cash<before.cash);assert.equal(result.state.transactions[0].category,'aircraft');assert.match(result.state.fleet[0].id,/^AC-/);});

test('saldo insuficiente impede compra sem alterar o estado',()=>{const before=game();before.cash=1;const result=acquireAircraft(before,'c208','new');assert.ok(result.error);assert.equal(result.state.fleet.length,0);assert.equal(result.state.cash,1);});

test('criação de rota gera scheduler recorrente integrado',()=>{const acquired=acquireAircraft(game(),'c208','new').state;const aircraft=acquired.fleet[0];const result=createRoute(acquired,{destination:'GIG',aircraftId:aircraft.id,fare:350,frequency:2,businessShare:0,firstShare:0});assert.equal(result.error,undefined);assert.equal(result.state.routes.length,1);assert.equal(result.state.schedules.length,1);assert.equal(result.state.schedules[0].departureTimes.length,2);assert.equal(result.state.schedules[0].active,true);});

test('simulação offline conclui voos uma única vez e atualiza economia',()=>{let state=acquireAircraft(game(),'c208','new').state;state=createRoute(state,{destination:'GIG',aircraftId:state.fleet[0].id,fare:350,frequency:1,businessShare:0,firstShare:0}).state;const now=Date.now();state.lastSimulationAt=now-2*86_400_000;const first=processSimulation(state,now);assert.ok(first.report.flights>=2);assert.ok(first.state.stats.flights>=2);assert.ok(first.state.transactions.some(t=>t.category==='flight_revenue'));const flights=first.state.stats.flights;const second=processSimulation(first.state,now);assert.equal(second.state.stats.flights,flights);});

test('validador aceita save atual e rejeita objeto corrompido',()=>{assert.equal(validateGame(game()),true);assert.equal(validateGame({cash:Number.NaN,version:1}),false);});

test('perfil executivo aceita somente avatares disponíveis',()=>{const before=game(),updated=setCompanyAvatar(before,4);assert.equal(updated.error,undefined);assert.equal(updated.state.company.avatarId,4);assert.equal(setCompanyAvatar(before,7).error,'Avatar inválido.');});

test('migração acrescenta mercado, concorrentes e histórico sem invalidar save antigo',()=>{const old=game() as GameState;delete (old as Partial<GameState>).marketState;delete (old as Partial<GameState>).competitors;delete (old as Partial<GameState>).flightLog;const migrated=hydrateGameState(old);assert.equal(migrated.competitors.length,4);assert.equal(migrated.marketState.demandIndex,1);assert.deepEqual(migrated.flightLog,[]);});

test('contingência encerra evento e registra custo',()=>{const before=game();before.events.push({id:'EV-TEST',title:'Teste',description:'Evento de teste',severity:'warning',startedAt:Date.now()-1000,expiresAt:Date.now()+100000,resolved:false,demandImpact:-.1,delayImpact:.2,fuelImpact:0,mitigationCost:1000});const result=mitigateEvent(before,'EV-TEST');assert.equal(result.error,undefined);assert.equal(result.state.events[0].resolved,true);assert.equal(result.state.cash,before.cash-1000);});

test('empréstimo pode ser amortizado e aparece na demonstração financeira',()=>{const financed=takeLoan(game(),2_000_000).state;const result=repayLoan(financed,financed.loans[0].id,500_000);assert.equal(result.state.loans[0].balance,1_500_000);const statement=financialStatement(result.state);assert.equal(statement.days,30);});

test('save legado recebe hubs, cabine, mercado, contratos e conquistas',()=>{const before=acquireAircraft(game(),'c208','new').state;delete (before as Partial<GameState>).hubs;delete (before as Partial<GameState>).infrastructure;delete (before as Partial<GameState>).aircraftMarket;delete (before as Partial<GameState>).contracts;delete (before as Partial<GameState>).achievements;delete (before.fleet[0] as Partial<typeof before.fleet[0]>).cabin;const after=hydrateGameState(before);assert.deepEqual(after.hubs,['GRU']);assert.equal(after.infrastructure[0].airportIata,'GRU');assert.ok(after.fleet[0].cabin.economy>0);assert.ok(after.aircraftMarket.length>0);assert.ok(after.contracts.length>0);assert.ok(after.achievements.some(item=>item.unlockedAt));});

test('oferta usada entra na frota e sai do mercado sem reaparecer ao carregar',()=>{const before=game();const offer=before.aircraftMarket.find(item=>item.acquisition==='used'&&item.modelId==='c208')||before.aircraftMarket.find(item=>item.acquisition==='used')!;const after=acquireMarketOffer(before,offer.id);if(after.error){assert.match(after.error,/nível|pista|caixa/);return;}assert.equal(after.state.fleet[0].ageYears,offer.ageYears);assert.equal(after.state.fleet[0].condition,offer.condition);assert.ok(!after.state.aircraftMarket.some(item=>item.id===offer.id));assert.ok(!hydrateGameState(after.state).aircraftMarket.some(item=>item.id===offer.id));});

test('cabine rejeita excesso de espaço premium e aceita layout viável',()=>{const before=acquireAircraft(game(),'a320neo','new');if(before.error){const small=acquireAircraft(game(),'c208','new').state;assert.ok(configureCabin(small,small.fleet[0].id,{economy:0,premiumEconomy:0,business:0,first:9}).error);assert.equal(configureCabin(small,small.fleet[0].id,{economy:8,premiumEconomy:0,business:0,first:0}).error,undefined);return;}const state=before.state,model=state.fleet[0];assert.ok(configureCabin(state,model.id,{economy:180,premiumEconomy:0,business:20,first:0}).error);assert.equal(configureCabin(state,model.id,{economy:140,premiumEconomy:10,business:15,first:1}).error,undefined);});

test('hub secundário exige nível 2 e infraestrutura amplia portões',()=>{const before=game();assert.ok(openHub(before,'GIG').error);before.stage=2;const opened=openHub(before,'GIG');assert.equal(opened.error,undefined);assert.ok(opened.state.hubs.includes('GIG'));const upgraded=upgradeInfrastructure(opened.state,'GIG','terminal');assert.equal(upgraded.error,undefined);assert.equal(upgraded.state.infrastructure.find(item=>item.airportIata==='GIG')?.gates,4);});

test('rota nova gera missão para destino e permite aceitar e resgatar',()=>{let state=acquireAircraft(game(),'c208','new').state;state=createRoute(state,{destination:'GIG',aircraftId:state.fleet[0].id,fare:350,frequency:1,businessShare:0,firstShare:0}).state;const offer=state.contracts.find(item=>item.status==='offered'&&item.destination==='GIG');assert.ok(offer);const accepted=acceptContract(state,offer!.id);assert.equal(accepted.error,undefined);assert.equal(accepted.state.contracts.find(item=>item.id===offer!.id)?.status,'active');const completed=accepted.state;completed.contracts.find(item=>item.id===offer!.id)!.status='completed';const reward=claimContract(completed,offer!.id);assert.equal(reward.error,undefined);assert.equal(reward.state.contracts.find(item=>item.id===offer!.id)?.status,'claimed');assert.ok(reward.state.cash>completed.cash);});
