'use client';

import { useEffect, useRef, useState } from 'react';
import { AIRPORTS, airportByIata } from './data';
import type { GameState } from './types';

declare global { interface Window { L?: any } }

function loadLeaflet(){return new Promise<void>((resolve,reject)=>{if(window.L){resolve();return;}if(!document.getElementById('leaflet-css')){const link=document.createElement('link');link.id='leaflet-css';link.rel='stylesheet';link.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(link);}const existing=document.getElementById('leaflet-js') as HTMLScriptElement|null;if(existing){existing.addEventListener('load',()=>resolve(),{once:true});existing.addEventListener('error',()=>reject(),{once:true});return;}const script=document.createElement('script');script.id='leaflet-js';script.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';script.onload=()=>resolve();script.onerror=()=>reject(new Error('Leaflet indisponível'));document.body.appendChild(script);});}

export default function WorldMap({game}: {game:GameState}){
  const host=useRef<HTMLDivElement>(null),mapRef=useRef<any>(null),layersRef=useRef<any[]>([]),[error,setError]=useState(false),[ready,setReady]=useState(false);
  const routeSignature=game.routes.map(route=>`${route.id}:${route.active}`).join('|');
  useEffect(()=>{let active=true;loadLeaflet().then(()=>{if(!active||!host.current||mapRef.current)return;const L=window.L;const base=airportByIata(game.company.base)!;const map=L.map(host.current,{zoomControl:false,worldCopyJump:true}).setView([base.latitude,base.longitude],game.routes.length?3:4);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:12,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);mapRef.current=map;setReady(true);setTimeout(()=>map.invalidateSize(),0);}).catch(()=>setError(true));return()=>{active=false;setReady(false);mapRef.current?.remove();mapRef.current=null;};},[]);
  useEffect(()=>{const L=window.L,map=mapRef.current;if(!ready||!L||!map)return;layersRef.current.forEach(layer=>map.removeLayer(layer));layersRef.current=[];const activeRoutes=game.routes.filter(r=>r.active),activeIatas=new Set([game.company.base,...activeRoutes.flatMap(r=>[r.origin,r.destination])]),focusPoints:any[]=[];for(const airport of AIRPORTS){if(!activeIatas.has(airport.iata)&&airport.size!=='major')continue;const isBase=airport.iata===game.company.base,active=activeIatas.has(airport.iata);const marker=L.circleMarker([airport.latitude,airport.longitude],{radius:isBase?8:active?6:2.6,color:isBase?'#59d6c7':active?'#7be4d8':'#71889b',weight:isBase?3:1,fillColor:isBase?'#59d6c7':active?'#21a997':'#38556c',fillOpacity:active?1:.55}).bindTooltip(`<b>${airport.iata}</b> · ${airport.city}<br>${airport.name}`);marker.addTo(map);layersRef.current.push(marker);if(active)focusPoints.push([airport.latitude,airport.longitude]);}for(const route of activeRoutes){const a=airportByIata(route.origin),b=airportByIata(route.destination);if(!a||!b)continue;const line=L.polyline([[a.latitude,a.longitude],[b.latitude,b.longitude]],{color:'#59d6c7',weight:2.4,opacity:.82,dashArray:'8 7'}).addTo(map);layersRef.current.push(line);}if(focusPoints.length>1)map.fitBounds(focusPoints,{padding:[32,32],maxZoom:5});else{const base=airportByIata(game.company.base)!;map.setView([base.latitude,base.longitude],4);}map.invalidateSize();},[ready,routeSignature,game.company.base]);
  if(error)return <div className="map-error"><b>Mapa online indisponível</b><span>O jogo continua acessível; verifique sua conexão para carregar o OpenStreetMap.</span></div>;
  return <div ref={host} className="leaflet-host" aria-label="Mapa operacional da companhia"/>;
}
